**IS110 - NumPyExercise**

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
%cd /content/drive/MyDrive/ColabNotebooks/

/content/drive/MyDrive/ColabNotebooks


In [4]:
!pwd

/content/drive/MyDrive/ColabNotebooks


#**Exercise A**

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

In [ ]:
import numpy as np

In [ ]:
A = np.array([[10, 20, 30], [40, 50, 60]])

In [ ]:
print("Shape of A:", A.shape)

Shape of A: (2, 3)


In [ ]:
print("Max value using method:", A.max())

Max value using method: 60


In [ ]:
print("Max value using np function:", np.max(A))

Max value using np function: 60


#**Exercise B**

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

In [ ]:
B = np.ones((5, 5), dtype=int)

In [ ]:
print(B)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
print("Shape:", B.shape)

Shape: (5, 5)


In [ ]:
print("Size:", B.size)

Size: 25


In [ ]:
print("Dimensions:", B.ndim)

Dimensions: 2


#**Exercise C**

In [ ]:
C = np.arange(-5, 6)

In [ ]:
result = C * 2

In [ ]:
print("Original Array:", C)

Original Array: [-5 -4 -3 -2 -1  0  1  2  3  4  5]


In [ ]:
print("Resulting Array:", result)

Resulting Array: [-10  -8  -6  -4  -2   0   2   4   6   8  10]


#**Push in NumPyExercise**

In [5]:
!ls "/content/drive/MyDrive/ColabNotebooks/"

 Buenafe.txt
 Chapter2.ipynb
 Chapter3.ipynb
 Chapter4.ipynb
'Copy of 01 Python Fundamentals, Part 1 (Workbook).ipynb'
'Copy of (IS110)Using_Git on Google Colab.ipynb'
'Copy of IS110 - Using_Git on Google Colab.ipynb'
'Copy of PythonEnvi.ipynb'
 Dashboard_Buenafe
 IS110_BPerformance_Buenafe
 IS110_repo_Jamile
 NumPyExercise.ipynb
 PythonEnvi_Buenafe


cp: cannot stat '/content/drive/MyDrive/ColabNotebooks/NumPyExcercise.ipynb': No such file or directory


In [ ]:
!ls

 Buenafe.txt
 Chapter2.ipynb
 Chapter3.ipynb
 Chapter4.ipynb
'Copy of 01 Python Fundamentals, Part 1 (Workbook).ipynb'
'Copy of (IS110)Using_Git on Google Colab.ipynb'
'Copy of IS110 - Using_Git on Google Colab.ipynb'
'Copy of PythonEnvi.ipynb'
 Dashboard_Buenafe
 IS110_BPerformance_Buenafe
 IS110_repo_Jamile
 NumPyExercise.ipynb
 PythonEnvi_Buenafe
